source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'gnawrnip'
gem 'faker', '~>1.6.3'
gem 'ffaker', '~>2.2.0'
gem 'capybara'

# Specify your gem's dependencies in my_first_gem.gemspec
gemspec
